server:
  port: 8081
  # Tomcat threads count, for performance tests
  #tomcat.max-threads: 10

spring:
  main:
    banner-mode: "off"
  data:
    mongodb:
      uri: mongodb://localhost/insurance

logging:
  level:
    ROOT: INFO
    com.adeliosys: DEBUG
    #org.springframework: DEBUG
    #org.springframework.security: DEBUG
  pattern:
    # Custom format: removed the date, added the request ID
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%6X{requestId}]){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
